import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
normal.family = "MesloLGS NF"
size = 16
