#!/usr/bin/env bash

# Function to create a symbolic link
create_symlink() {
	local source_file="$1"
	local target_file="$2"

	ln -sf "$source_file" "$target_file"
}

# Get the current working directory
current_dir=$(pwd)

# Symlink nvim config
create_symlink "${current_dir}/.config/nvim" "${HOME}/.config/nvim"

# Symlink tmux config
create_symlink "${current_dir}/.config/tmux" "${HOME}/.config/tmux"

# Symlink zsh config
create_symlink "${current_dir}/.config/zsh" "${HOME}/.config/zsh"
